- hosts: all
  remote_user: root
  vars_files:
    - "../../db/network.yml"
    - "../../db/storage.yml"
  tasks:

#  - debug:
#      msg: "{{ item.vlan97.vmbr0 }}"
#    with_items: "{{ trax }}"

  - name: /etc/hosts
    template: src="template/etc/hosts.j2" dest="{{ item.hostname }}/etc/hosts"
    with_items: "{{ trax_network }}"

  - name: /etc/network/interfaces
    template: src="template/etc/network/interfaces.j2" dest="{{ item.hostname }}/etc/network/interfaces"
    with_items: "{{ trax_network }}"

  - name: /etc/fstab
    template: src="template/etc/fstab.j2" dest="{{ item.hostname }}/etc/fstab"
    with_items: "{{ trax_storage }}"
