---
all:
  hosts:
    192.168.95.21:
      name: rproxy
      ansible_become: true
      ansible_become_user: root
      ansible_become_method: su
      ansible_user: exo
      ansible_ssh_pass: temp
      ansible_become_pass: temp
    192.168.95.22:
      name: publica
      ansible_become: true
      ansible_become_user: root
      ansible_become_method: su
      ansible_user: exo
      ansible_ssh_pass: temp
      ansible_become_pass: temp
    192.168.95.23:
      name: privada
      ansible_become: true
      ansible_become_user: root
      ansible_become_method: su
      ansible_user: exo
      ansible_ssh_pass: temp
      ansible_become_pass: temp
    192.168.95.24:
      name: core
      ansible_become: true
      ansible_become_user: root
      ansible_become_method: su
      ansible_user: exo
      ansible_ssh_pass: temp
      ansible_become_pass: temp
    192.168.95.27:
      name: rt
      ansible_become: true
      ansible_become_user: root
      ansible_become_method: su
      ansible_user: exo
      ansible_ssh_pass: temp
      ansible_become_pass: temp
    192.168.95.28:
      name: secon
      ansible_become: true
      ansible_become_user: root
      ansible_become_method: su
      ansible_user: exo
      ansible_ssh_pass: temp
      ansible_become_pass: temp
