---
# ahora imagínate una página web que edita este yaml
# note: numbers as keys are problematic

#   # Networking
#   
#   ## Pla de VLANs amb FXOLN
#   
#   Estats de les VLANs:
#   
#   - Provisional: en fase de disseny, pendent d'aprovar disseny, pendent de demanar a FXOLN
#   - Assignada: aplicada per XFOLN; preparada per utilitzar
#   - En producció: en ús

network_ranges:
  range1: 109.69.8.64/26
  range2: 109.69.10.64/26
  range3: 2a00:1508:100:ffff::/64
    nota: on tenim els servers de la exo
  range4: 2a00:1508:100::/40
    nota: tot lo que tenim

vplan: # vlan plan
  vlan90:
    type: fxoln
    code: gfilan
    subnet: 10.38.140.224/27
    notes: prefix guifi de la eXO assignat al lloc acer30
  vlan91:
    type: fxoln
    code: gfiptp1
    subnet: 172.25.38.208/29
    notes: troncal per wifi amb Alambra
  vlan92:
    type: fxoln
    code: gfiptp2
    subnet: 172.25.45.8/29
    notes: troncal per wifi amb Ermita
  vlan93:
    type: fxoln
    code: gfiptp3
    subnet: 172.25.40.64/30
    notes: troncal per wifi amb Can Bruixa
  vlan10:
    type: fxoln
    code: gfiptp4
    subnet: 172.25.34.48/30
    notes: troncal amb FXOLN (BGP de 10.0.0.0/8)
  vlan102:
    type: fxoln
    code: ix
    subnet: 10.253.4.0/22
    notes: Internet Exchange amb FXOLN
  vlan94:
    type: fxoln
    code: dmz
    subnet: 192.168.94.0/24
    notes: servers accessibles des d'Internet amb IP pública
  vlan95:
    type: fxoln
    code: vctrl
    subnet: 192.168.95.0/24
    notes: vlan de control de màquines virtuals i tràfic entre màquines virtuals
  vlan96:
    type: fxoln
    code: pve
    subnet: 192.168.96.0/24
    notes: tràfic clúster proxmox
  vlan97:
    type: fxoln
    code: gfs
    subnet: 192.168.97.0/24
    notes: tràfic clúster gluster
  vlan98:
    type: fxoln
    code: hctrl
    subnet: 192.168.98.0/24
    notes: control·la les màquines físiques: trax[123]
  vlan127:
    type: internal
    code: ipmi
    subnet: 192.168.127.0/24
    notes: VLAN interna de IPMI
  vlan128:
    type: fxoln
    code: operador
    notes: la dona FXOLN, no sabem per què serveix

# identificadors VM comencen al 20
vms:
  - hostname: rproxy
    vlan90:
      ip: 10.38.140.232/27
      static_route_guifi: 10.38.140.225
      iface: eth1
    vlan94: 
      ip: 109.69.10.112/27
      gateway: 109.69.10.126
      iface: eth2
      ip6: 2a00:1508:100:ffff::3
      gateway6: 2a00:1508:100:ffff::1
    vlan95:
      ip: 192.168.95.21/24
      iface: eth0
  - hostname: publica
    vlan95:
      ip: 192.168.95.22/24
      gateway: 192.168.95.26
      iface: eth0
  - hostname: privada
    vlan95:
      ip: 192.168.95.23/24
      gateway: 192.168.95.26
      iface: eth0
  - hostname: core
    vlan95:
      ip: 192.168.95.24/24
      iface: eth0
    vlan90:
      # AQUESTA IP NO FUNCIONARÀ: està mapejada temporalment contra el vrouter2
      ip: 10.38.140.233/27
      iface: eth1
    vlan94:
      ip: 109.69.10.123/27
      gateway: 109.69.10.126
      ip6: 2a00:1508:100:ffff::4
      gateway6: 2a00:1508:100:ffff::1
      iface: eth2
  - hostname: rt
    vlan95:
      ip: 192.168.95.27/24
      iface: eth0
    vlan90:
      ip: 10.38.140.249/27
      iface: eth1
    vlan94:
      ip: 109.69.10.114/27
      iface: eth2
      ip6: 2a00:1508:100:ffff::d
      gateway6: 2a00:1508:100:ffff::1
  - hostname: vrouter
    iface_type: Intel E1000 # de moment està en virtio i funciona; provar més temps i avaluar
    vlan90:
      ip: 10.38.140.225/27
      iface: vmbr0 # dintre del bridge anirà la vlan 90 (?). al final del projecte no hauria d'existir el bridge
    vlan94:
      ip: 109.69.10.126/27 
    vlan98:
      ip: 192.168.98.1/24
    vlan102:
      ip: 10.253.4.28/22
      gateway: 10.253.4.21
  - hostname: vrouter2
    vlan95:
      ip: 192.168.95.26/24
      iface: eth0
    vlan98:
      ip: 192.168.98.26/24
      gateway: 192.168.98.1
      iface: eth1
  - hostname: secon # client 1
    vlan95:
      ip: 192.168.95.28/24
      iface: eth0
    vlan94:
      ip: 109.69.10.97/27
      iface: eth1
    vlan90:
      ip: 10.38.140.250/27
      iface: eth2
#    vlan90:
#    ip: 109.69.10.119/27 ?
# vpn trax admins
  - hostname: vpn
    vlan90:
      ip: 10.38.140.234/27
      iface: eth0
    vlan94:
      ip: 109.69.10.124/32
      iface: eth1
    vlan95:
      ip: 192.168.95.29/24
      iface: eth2
    vlan98:
      ip: 192.168.98.29/24
      iface: eth3
  - hostname: ttn
    vlan90:
      ip: 10.38.140.235/27
      iface: eth0
    vlan94:
      ip: 109.69.10.98/32
      iface: eth1
  - hostname: gradio
    vlan90:
      ip: 10.38.140.236/27
      iface: eth0
    vlan94:
      ip: 109.69.10.99/32
      iface: eth1
# next: free guifi IPs: 10.38.140.237 10.38.140.238


# tant de bo provisional
atom:
  - ip: 109.69.8.122/29
    comentari: ip de l'atom
  - ip: 10.38.140.254/27
    tipus: mapeig
    comentari: contra 109.69.8.122 (servidor atom) # per tal que tingui ip de guifi

hangar: #?


mikrotik:
  - vlan10:
      ip: 172.25.34.50/30
      bgp_peer: R3
      iface: vlan10_guifinet
      comentari: rutes guifi?
  - vlan90:
      ip: 10.38.140.225/27
      bridge_iface: wLan/Lan
        - iface: vlan90fundacio
  - vlan91:
      ip: 172.25.38.209/29
      bgp_peer: HW-Alambra
      bridge_iface: bridgeVlan91
        - iface: vlan91fundacio
  - vlan92:
      ip: 172.25.45.12/29
      bgp_peer: Ermita
      bridge_iface: bridgeVlan92
        - iface: vlan92fundacio
  - vlan93:
      ip: 172.25.40.65/30
      bgp_peer: Can Bruixa
      bridge_iface: bridgeVlan93
        - iface: vlan93fundacio
  - vlan94:
      ip: 109.69.10.126/27
      bridge_iface: bridgeVlan94
        - iface1: vlan94_srv
        - iface2: eoip-srv_p9
      comentari: aquí es on hi ha els servidors
  - vlan98:
      ip: 192.168.98.1/24
      iface: vlan89_hctrl
  - vlan102:
      ip: 10.253.4.28/22
      bgp_peer: fundacio
      iface: vlan102_transitPOP
  - vlan128:
      comentari: no assignat

# identificadors trax en el domini de 10
trax_network:
  - hostname: trax1
    temp:
      guifi: 10.38.140.230 # accessing trax via mikrotik
    gluster: gfs1
    vlan96:
      ip: 192.168.96.11/24
      iface: vmbr0
    vlan97:
      ip: 192.168.97.11/24
      iface: vmbr0
    vlan98:
      ip: 192.168.98.11/24
      ipmi: 192.168.98.21/24
      gateway: 192.168.98.1
    vlan127: # vlan interna, connectada a mikrotik/trax3
      ipmi: 192.168.127.11/24
  - hostname: trax2
    ipv6_linklocal: fe80::3ad5:47ff:fec9:6b37
    temp:
      guifi: 10.38.140.231 # accessing trax via mikrotik
    gluster: gfs2
    vlan96:
      ip: 192.168.96.12/24
      iface: vmbr0
    vlan97:
      ip: 192.168.97.12/24
      iface: vmbr0
    vlan98:
      ip: 192.168.98.12/24
      ipmi: 192.168.98.22/24
      iface: vmbr0
      gateway: 192.168.98.1
    vlan127: # vlan interna, connectada a mikrotik/trax3
      ipmi: 192.168.127.12/24

support: # nodes that support the cluster
  - hostname: mikrotik # provisional
    vlan102:
      ip: 10.253.4.28/22
      iface: vmbr0
      gateway: 10.253.4.21
    vlan127: # vlan interna, connectada a mikrotik/trax3
      ip: 192.168.127.13/24
      iface: vmbr0
  - hostname: trax3
    loopback: 109.69.10.96
    vlan96:
      ip: 192.168.96.13/24
      iface: vmbr0
    vlan97:
      ip: 192.168.97.13/24
      iface: vmbr0
    vlan98:
      ip: 192.168.98.13/24
      iface: vmbr0
      gateway: 192.168.98.13
    vlan102: # pendent de confirmar amb FXOLN
      ip: 10.253.4.29/22
      iface: vmbr0
      gateway: 10.253.4.21
    vlan127: # vlan interna, connectada a mikrotik/trax3
      ipmi: 192.168.127.13/24


### VMs?

# ## Gateways
# 
# De situació temporal a situació definitiva
# 
# trax1 i trax2 surten per Mikrotik a través de VLAN98
# 
# després ho faran per atom (trax3) a travé de la mateixa VLAN98
# 
# la justificació d'això és que no trobem eficient que vagi de la màquina host a la màquina virtual de routing per tornar a sortir al host
